language: android
sudo: false
android:
  components:
    - build-tools-20.0.0
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_cb6c1fbf7ffb_key -iv $encrypted_cb6c1fbf7ffb_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/dab34968484f08aa6a33
    on_success: change
    on_failure: always
    on_start: never
