language: android
sudo: false
install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-25.0.2
  - echo y | android update sdk -u -a -t android-25
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_cb6c1fbf7ffb_key -iv $encrypted_cb6c1fbf7ffb_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/dab34968484f08aa6a33
    on_success: change
    on_failure: always
    on_start: never
